name: tabbed_view_demo
description: TabbedView Demo

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tabbed_view: #^2.0.0-rc.7
    path: ../tvmr
  demoflu: ^2.5.0
    #path: ../demoflu

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/pages/
    - lib/pages/get_started/
    - lib/pages/content_builder/
    - lib/pages/close_button_tooltip/
    - lib/pages/tab/
    - lib/pages/tab/button/
    - lib/pages/tab/button/icon_data/
    - lib/pages/tab/button/icon_path/
    - lib/pages/tab/button/menu/
    - lib/pages/tab/draggable/
    - lib/pages/tab/non_closable/
    - lib/pages/tab/keep_alive/
    - lib/pages/tab/tab_leading/
    - lib/pages/tab/tab_remove_interceptor/
    - lib/pages/tab/tab_remove_listener/
    - lib/pages/tab/tab_selection_listener/
    - lib/pages/tab/tab_selection_interceptor/
    - lib/pages/tab/tab_programmatically/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
